examples/fly/Dockerfile
Bullseye doesn't have the right glibc for the latest builds.
=> Update Fly.io example Dockerfile to use Debian Bookworm

examples/fly/Dockerfile, examples/fly/config.toml, examples/fly/entrypoint.sh, examples/fly/fly.toml, examples/fly/schemas/tests.sql, examples/fly/schemas/todo.sql
* Dockerfile:
* add sqlite3 so generic exercises in the quick-start doc work
* put files into conventional locations on the Machine: not so many flags needed and corrosion binary is in PATH
* don't switch users yet, so root can run entrypoint script and edit the config file in /etc
* Matching changes to entrypoint.sh and config.toml
* Change app name to corrosion in fly.toml
* Replace schema with the todo example from docs
=> fly.io example updates

CHANGELOG.md, crates/corro-agent/src/api/public/mod.rs, crates/corro-types/src/pubsub.rs, crates/corro-types/src/schema.rs
This PR adds a feature where an existing table can be used as part of the Corrosion schema. Meaning all future operations will be propagated, but it is assumed that the state of the database from which the node started is consistent across all nodes.
=> Support using an existing table schema

crates/corro-agent/src/agent.rs
Temporary measure to not trash performance until we have a better hashing strategy.
=> Don't hash tables with > 500K rows

crates/corro-agent/src/api/public/mod.rs, crates/corro-agent/src/api/public/pubsub.rs, crates/corro-api-types/src/lib.rs, crates/corro-client/src/sub.rs, crates/corro-types/src/pubsub.rs, crates/corrosion/src/main.rs, doc/api/subscriptions.md
A few untested cases caused issues, fixed and:
- Added a `change_id` property on End Of Query which makes clients more efficient.
- Added more docs for completeness.
=> Persistent subscriptions weren't resumed properly

CHANGELOG.md, crates/corrosion/src/command/consul/sync.rs
This should improve consul data consistency as changes won't be applied until both services and checks data are received. Matching checks should have the right state for the current services.
=> Bundle consul services and checks in the same transaction

crates/corro-agent/src/agent.rs, crates/corro-types/src/agent.rs
This aims at reducing the possibilities of stalling w/ the following:
- Don't interrupt long-running SQLite executions. They're pretty much always necessary. The only way that would be problematic is if we have a deadlock in Corrosion within a transaction.
- Rewrite the compaction logic to do a single-ish query to get all cleared versions
- Keep synchronizing in a loop until a synchronization completes successfully.
=> Remove possible blockages

Cargo.lock, Cargo.toml, crates/corro-admin/src/lib.rs, crates/corro-agent/src/agent.rs, crates/corro-agent/src/api/peer.rs, crates/corro-agent/src/api/public/mod.rs, crates/corro-agent/src/broadcast/mod.rs, crates/corro-api-types/src/lib.rs, crates/corro-types/src/actor.rs, crates/corro-types/src/agent.rs, crates/corro-types/src/broadcast.rs, crates/corro-types/src/members.rs, crates/corro-types/src/pubsub.rs, crates/corro-types/src/schema.rs, crates/corro-types/src/sync.rs, crates/corrosion/src/main.rs
This PR brings back a previously failed attempt at batch inserting many multiple changesets in the same transaction.
An issue happened where sometimes we'd get the same `db_version` for different changesets from the same Corrosion node. This is now fixed w/ a workaround (but reported to cr-sqlite) by incrementing the `crsql_db_version` by 1 more on each changeset.
This PR also batch inserts empty changesets, they're stored in-memory right away, but we can delay inserting.
For debugging purposes, we've also added a way to track lock durations by label. This helped debug deadlocks. In a future release these should be removed.
=> Batch insertions

crates/corro-agent/src/agent.rs, crates/corro-agent/src/api/peer.rs, crates/corro-agent/src/transport.rs, crates/corro-types/src/config.rs, crates/corro-types/src/pubsub.rs
Changes:
- Keep connections open longer to improve the cluster's reliability and speed.
- Add a few more connection-related metrics
- Had forgotten to process changes for subscribers in the case of applying buffered changes, this is now fixed.
=> Clustering tweaks

crates/corro-agent/src/transport.rs, crates/corro-types/src/agent.rs, crates/corro-types/src/sync.rs
This was overloading our traces cluster
=> Vastly reduce the number of traces sent

Cargo.lock, Cargo.toml, crates/corro-agent/src/agent.rs, crates/corro-agent/src/api/public/mod.rs, crates/corro-agent/src/api/public/pubsub.rs, crates/corro-api-types/src/lib.rs, crates/corro-api-types/src/sqlite.rs, crates/corro-pg/Cargo.toml, crates/corro-pg/src/lib.rs, crates/corro-tpl/src/lib.rs, crates/corro-types/Cargo.toml, crates/corro-types/src/agent.rs, crates/corro-types/src/config.rs, crates/corro-types/src/pubsub.rs, crates/corro-types/src/schema.rs, crates/corro-types/src/sqlite.rs, crates/corrosion/src/main.rs
Subscriptions were affecting the main database because there was only 1 subscriptions database and it was being `ATTACH`ed. Any writes to either would lock both.
These changes greatly improve subscriptions performances by:
- Using a dedicated SQLite database per subscription
- Never writing to the main database or to the subscription database when attached (therefore preventing any write locks from occurring)
=> Subscriptions performance improvements

Cargo.lock, Cargo.toml, crates/corro-agent/src/api/public/pubsub.rs, crates/corro-api-types/src/lib.rs
Corrosion was not waiting for the rows channel to fully drain before starting to send changes.
Fixes #89
=> Fix high-frequency changes skips on re-subscription

crates/corro-client/src/lib.rs, crates/corro-client/src/sub.rs
This may happen while re-subscribing with a known change ID that's already
become stale. In this case, allow the very first change set in the newly
created subscription to be non-contiguous and enfore the rule for all
subsequent change sets.
=> Allow the first change set in a sub to be non-contiguous

crates/corro-agent/src/agent.rs, crates/corro-agent/src/api/public/mod.rs, crates/corro-agent/src/api/public/pubsub.rs, crates/corro-api-types/src/lib.rs, crates/corro-pg/src/lib.rs, crates/corro-types/src/agent.rs, crates/corro-types/src/pubsub.rs
Some operations may return a "database locked" error from the main connection if we're not using the write semaphore to acquire a permit first.
This PR also batches changes to reduce I/O for subscriptions.
=> Use the write semaphore in subscription logic

crates/corro-agent/src/api/public/pubsub.rs, crates/corro-types/src/pubsub.rs
Subscribers could stay connected but never receive anything if a subscription was cancelled. This should close the chain of channels and ultimately the connection when a subscription is cancelled.
=> Cancel subscribers byte forwarding when a subscription is cancelled

Cargo.lock, crates/corro-agent/src/agent.rs, crates/corro-agent/src/api/peer.rs, crates/corro-agent/src/api/public/mod.rs, crates/corro-agent/src/lib.rs, crates/corro-api-types/src/lib.rs, crates/corro-base-types/Cargo.toml, crates/corro-base-types/src/lib.rs, crates/corro-pg/src/lib.rs, crates/corro-tpl/src/lib.rs, crates/corro-types/Cargo.toml, crates/corro-types/src/agent.rs, crates/corro-types/src/base.rs, crates/corro-types/src/broadcast.rs, crates/corro-types/src/change.rs, crates/corro-types/src/lib.rs, crates/corro-types/src/pubsub.rs, crates/corro-types/src/sqlite.rs, crates/corro-types/src/sync.rs, crates/corrosion/src/main.rs, rust-toolchain.toml
This should prevent any confusing when passing around similar integer types.
It will also create hard errors when loading non-u64 from SQLite when they should always be non-negative.
This change requires moving to nightly in order to implement the `std::iter::Step` trait for use to iterate on newtypes' ranges.
It might be possible to feature-gate it, but I haven't bothered for now.
=> Use `u64` newtypes

flake.lock, flake.nix
- pull in a pinned version of the rust nightly toolchain (2023-12-03)
- run `nix flake update` to update dependencies
- run `nix build` to build the corrosion package output
- run `nix develop` to enter a bash shell with all required dependencies in scope
=> Add nix flake build environment

crates/corro-agent/src/api/public/pubsub.rs
Make sure read lock is dropped before taking the write lock.
=> Fix deadlock in case an unknown subscription is requested by ID

crates/corro-agent/src/agent.rs, crates/corro-agent/src/api/peer.rs, crates/corro-agent/src/api/public/mod.rs, crates/corro-tests/src/lib.rs, crates/corro-types/src/agent.rs
Attempt at fixing a scenario where partials might be wrong. We haven't seen that in the wild, but the write lock isn't held properly for that data to be trusted.
This also adds better tracking of `__corro_seq_bookkeeping` and a more thorough `large_tx_sync` test.
=> Fix partials inconsistencies

flake.nix
You can serve the docs book locally with: nix develop .#mdbook-shell
=> flake: add mdbook dependencies target

crates/corro-admin/src/lib.rs, crates/corro-agent/src/agent/bi.rs, crates/corro-agent/src/agent/handlers.rs, crates/corro-agent/src/agent/metrics.rs, crates/corro-agent/src/agent/run_root.rs, crates/corro-agent/src/agent/setup.rs, crates/corro-agent/src/agent/tests.rs, crates/corro-agent/src/agent/uni.rs, crates/corro-agent/src/agent/util.rs, crates/corro-agent/src/api/peer.rs, crates/corro-agent/src/api/public/mod.rs, crates/corro-pg/src/lib.rs, crates/corro-tests/src/lib.rs, crates/corro-types/src/agent.rs, crates/corrosion/src/command/agent.rs
Loading the full bookkeeping of versions in memory can be time and resources consuming. This slows down accepting and processing public API endpoints such as transaction, queries, subscriptions, etc. and can create odd-looking behaviour.
This PR tries to spawn as many tasks as possible (all the ones that don't need access to the full bookkeeping), seed `Bookie` and then launch the tasks that need complete in-memory bookkeeping.
This should significantly improve startup times. It should be instantaneous for nodes that don't have any local versions.
=> Separate Bookie instantiation to listen on public API faster

crates/corro-agent/src/agent/util.rs
This adds a rather noticeable latency ~40ms to each HTTP request if
there is a constant stream of them.
=> api: disable Nagle's algorithm for HTTP API

crates/corro-types/src/pubsub.rs
The PR attempts to optimize Corrosion subscriptions with complex queries with `LEFT JOIN`s. Consider the following query:
```
SELECT
cs.id, cc.status, m.status as machine_state
FROM
consul_services AS cs
LEFT OUTER JOIN
machines m ON m.id = cs.instance_id
LEFT OUTER JOIN
consul_checks AS cc INDEXED BY consul_checks_node_service_id ON cc.node = cs.node AND cc.service_id = cs.id
```
This is a slightly simplified version of the query that `fly-proxy` needs to subscribe to (in real life, `fly-proxy` selects many more columns).
For the given query Corrosion will generate three modified queries (one for each table) to determine whether a particular set of changes matches the subscription or not. Unfortunatelly, due to `LEFT OUTER JOIN`, the modified queries for `machines` and `consul_checks` …
=> RFC: Rewrite LEFT JOINs in Corrosion subscriptions

crates/corro-agent/src/api/peer.rs, crates/corro-agent/src/transport.rs, crates/corro-types/src/config.rs
Using an unspecified IP can sometimes cause issues, especially if your hosts have a lot of network interfaces. With this configuration option, it's possible to set a specific addr or a specific ip with port 0 to keep the pooling features.
Even on hosts with only a few network interface, this can result in faster `sendmmsg` calls.
=> Configurable client addr for outgoing socket bind

Cargo.lock, Cargo.toml, crates/corro-admin/src/lib.rs, crates/corro-agent/src/agent/handlers.rs, crates/corro-agent/src/agent/run_root.rs, crates/corro-agent/src/agent/util.rs, crates/corro-agent/src/broadcast/mod.rs, crates/corro-types/src/agent.rs, crates/corrosion/src/main.rs
Whew...
- Adds a command `actor version <actor id> <version>` to inspect the state of a version in-memory.
- Fixes a mistaken SQL query meant to squash `__corro_seq_bookkeeping` rows (forgot a `RETURNING` on the `DELETE`).
- Disables detection of cleared versions for now
- Changes the `busy_timeout` before truncating the WAL periodically and then restores it.
- Tweaks a few values for processing changes more efficiently (should be made configurable)
=> Troubleshooting tools and buffered changes fixes

crates/corro-types/src/pubsub.rs
They are semantically the same as LEFT OUTER JOINs, but the parser
creates separate tokens for them.
=> Apply the same optimizations to LEFT JOINs in subs

crates/corro-api-types/src/lib.rs
So it can act as a key in a hash map.
=> Derive Hash for RowId

doc/deploy-on-fly/launch.md, examples/fly/Dockerfile
Changes Dockerfile to use bookworm not latest for rust builder.
Updates docs to not checkout v0.1.0
Fixes ##171
Tested (destroyed the previous machine and volume and followed through doc launch steps after these changes)
=> Fix deploy-on-fly

Cargo.lock, crates/corro-types/Cargo.toml, crates/corro-types/src/sqlite.rs, crates/sqlite-functions/Cargo.toml, crates/sqlite-functions/src/lib.rs
This PR introduces a way to insert custom API functions into SQLite
connections available to API queries and subscriptions. And implements
first such custom function.
The function allows to check whether a JSON object is fully contained
inside another JSON object and will be used to match machine metadata
with FKS service selector in a subscription.
=> Custom SQLite functions for API queries/subscriptions

crates/corro-agent/src/api/public/pubsub.rs
When a new subscription is created, the data is sent directly to the
broadcast channel. If this channel overflows because the receiver is
not fast enough, the error is not detected by `select!` and the client
is left hanging forever.
Fix the error detection, so that the client can actually re-subscribe.
Since it re-subscribes with existing subscription, the initial data
is sent to the mpsc channel that doesn't suffer from the overflow
issue.
=> Work around channel overflow for freshly created subscriptions

Cargo.lock, Cargo.toml, crates/corro-admin/src/lib.rs, crates/corro-agent/src/agent/handlers.rs, crates/corro-agent/src/agent/mod.rs, crates/corro-agent/src/agent/run_root.rs, crates/corro-agent/src/agent/setup.rs, crates/corro-agent/src/agent/tests.rs, crates/corro-agent/src/agent/util.rs, crates/corro-agent/src/api/peer.rs, crates/corro-agent/src/api/public/mod.rs, crates/corro-api-types/src/lib.rs, crates/corro-devcluster/src/main.rs, crates/corro-devcluster/src/topology/mod.rs, crates/corro-pg/src/lib.rs, crates/corro-types/src/agent.rs, crates/corro-types/src/broadcast.rs, crates/corro-types/src/config.rs, crates/corro-types/src/sync.rs, crates/corrosion/Cargo.toml, crates/corrosion/src/command/agent.rs, crates/corrosion/src/main.rs, crates/sqlite3-restore/src/lib.rs
This adds some more data in sqlite to keep memory usage down and reduce time-to-start-syncing considerably.
=> Do not load _everything_ in memory for bookkeeping

crates/corro-pg/src/lib.rs
This returned the wrong number of rows affected most of the time because it was actually getting SQLite `changes` count from the nearest INSERT / UPDATE / DELETE which was likely __corro_bookkeeping_gaps or __corro_bookkeeping!
=> Postgres logic should gather "rows affected" before commit logic

.buildkite/test.sh, crates/corro-agent/src/agent/tests.rs, crates/corro-agent/src/agent/util.rs, crates/corro-agent/src/api/peer.rs
There was a big consistency issue with storing emptied versions. Some ranges were mistakenly collapsed causing versions to be wrongly marked as cleared.
This PR:
- Adds tests and fixes the inconsistency issues
- Bundles cleared versions so they're sent as chunks, easier to process for sync clients.
=> Correct storing of empty versions

crates/corro-agent/src/agent/tests.rs
This pull request calculates the max version for each node correctly at the end of stress tests and adds more logs to make it easier to figure out what caused the stress test to fail
=>  Properly calculate max version in stress_test

crates/corro-client/src/lib.rs
Make sure the client is able to quickly detect a dead connection.
=> corro-client: enable HTTP2 keep-alives

crates/corro-agent/src/agent/util.rs
As mention in the [sqlite3 documentation](https://www.sqlite.org/lang_transaction.html), when certain errors occur within a transaction, it may or may not be automatically rolled back.
This resolves an issue where a transaction fails but some rows are committed to the gaps db, causing a drift between the in-memory and database gaps.
=> Stop processing changeset on sqlite error

crates/corro-agent/src/api/public/pubsub.rs
So the last sent row and the last change ID values are consistent.
Otherwise it might skip all the changes happened between reading the rows
and querying the last change ID.
=> pubsub: make sure to catch up sub in a transaction

crates/corro-agent/src/agent/handlers.rs, crates/corro-agent/src/agent/run_root.rs, crates/corro-types/src/sqlite.rs
Running `PRAGMA wal_checkpoint(TRUNCATE)` can be pretty expensive. Instead of running it on a timer, running it if its size is above a certain threshold makes more sense.
This should be made configurable..
=> Truncate WAL if size above threshold

crates/corro-client/src/lib.rs, crates/corro-client/src/sub.rs
The PR fixes client's behavior to return an error if the change ID provided to subscription handler
is too old and already recycled on the server side.
The PR also introduces DNS resolve timeout to make sure something is printed to the logs if DNS resolve
takes too much time.
=> Return error of provided change ID is too old

crates/corro-agent/src/api/public/pubsub.rs
Make sure to update minimum expected change ID when retrying catch up
so that it can actually proceed if the first attempt fails.
=> pubsub: fix catch up logic

crates/corro-client/src/sub.rs
We still get them and it's not clear what's going on. Maybe known
the actual change IDs will help.
=> corro-client: add expected and received change ID to MissedChange error

crates/corro-agent/src/api/public/pubsub.rs
The order of events processing when Corrosion is handling a change is:
- determine changes
- send changes to the channel
- commit changes to sub DB
When Corrosion client is catching up it subscribes to changes sent to
the channel and queries the full sub DB. It's possibly that the query
is run *before* the changes are committed, but after they've been sent
to the channel, so what happens is:
* A change with ID N is processed by Corrosion and sent to the channel
* catch up logic starts and subscribes to changes, but doesn't see
this change
* sub DB is read and sent to the client, last committed change ID is
N - 1, so EndOfQuery{change_id: N - 1} is sent to the client
* corrosion commits the last update so the last change in the DB becomes
N
* catch up handler has min_change_id = N - 1 + 1, …
=> pubsub: fix a subtle race in catch up logic for barely active subs

crates/corro-client/src/sub.rs
Change ID still needs to be incremented even if the entry is not valid.
=> corro-client: handle deserialization error correctly

crates/corro-agent/src/agent/util.rs
this fixes the panic in debug build:
thread 'tokio-runtime-worker' panicked at crates/corro-types/src/agent.rs:1306:9:
max value was not applied
steps to reproduce:
- schema
CREATE TABLE todos ( id INTEGER NOT NULL PRIMARY KEY, title TEXT NOT NULL DEFAULT '' );
- node A
./corrosion -c corro.toml exec 'INSERT INTO todos (id, title) VALUES (1, "test todo")'
- node B
./corrosion -c corro.toml query 'SELECT * FROM todos' ./corrosion -c corro.toml exec 'DELETE FROM todos WHERE id == 1'
now node A crashes with assert message `max value was not applied`
=> manually drop snapshot without running its destructor

crates/corro-agent/src/agent/handlers.rs, crates/corro-agent/src/agent/tests.rs, crates/corro-agent/src/api/peer.rs, crates/corro-types/src/agent.rs, crates/corro-types/src/members.rs, crates/corro-types/src/sync.rs
When a node processes empties slowly, we can end up requesting already received empties that are still in the buffer. This pull request adds a field to the Members struct to store the last received empties timestamp and use that instead when requesting so we would not request an empty that we already have.
=> Store and use last seen empty timestamp when requesting for empties

crates/corro-pg/src/lib.rs
It's possible to infer better return typed from queries based on the function that's being called, the casting or if the column is a literal (e.g. `SELECT 1` should return a single field of type `Int8`).
This allows more PG clients and use cases to work properly.
=> Override some PG field types from a parsed query

crates/corro-agent/src/api/public/pubsub.rs, crates/corro-types/src/pubsub.rs, crates/corro-types/src/schema.rs
Adjust pubsub code to use them instead of generated column names
=> Detect columns used in generated columns

crates/corro-devcluster/src/main.rs, crates/corrosion/src/main.rs
even though `#[clap()]` still works, `#[command()]` and `#[arg()]` are now recommended since clap v4, ref https://github.com/clap-rs/clap/pull/4180
=> replace clap attributes with command and arg

Cargo.lock, crates/corro-admin/Cargo.toml, crates/corro-admin/src/lib.rs, crates/corro-types/src/pubsub.rs, crates/corro-types/src/sync.rs, crates/corrosion/src/main.rs
```
somma@odysseus:~/workspace/superfly/corrosion$ target/debug/corrosion -c _personal/config.toml subs info --hash 6525eb339b115733
{
"hash": "6525eb339b115733",
"id": "fe4523c2-c1ef-4d49-99e7-cd35ac8632de",
"last_change_id": 0,
"original_query": "SELECT id,title,completed_at FROM todos",
"path": "./test-corrosion/subscriptions/fe4523c2c1ef4d4999e7cd35ac8632de",
"statements": [
{
"todos": "SELECT todos.id AS __corro_pk_todos_id, id AS col_0, title AS col_1, completed_at AS col_2 FROM todos WHERE (todos.id) IN __corro_sub.temp_todos"
}
]
}
```
=> Adds an info and list command for getting more details on subscriptions

crates/corro-agent/src/agent/handlers.rs, crates/corro-agent/src/agent/tests.rs, crates/corro-agent/src/agent/util.rs, crates/corro-agent/src/broadcast/mod.rs, crates/corro-types/src/config.rs
This pull request adds the following changes:
- The use of savepoints for commit single versions are handled within `process_multiple_changes` so if one version fails we can continue with the others. 
- It reverts the behaviour of removing failed versions from the seen map as this can cause duplicate changes from broadcasts to be re-sent. Now the changes will eventually be retried when the cache is cleared.
- We now maintain the same size for the both the cache and the queue, so that we never have duplicate items in the queue
=> Handle failed changes properly

crates/corrosion/src/command/consul/sync.rs
In retrospective `source` may not be the best name for the column, probably something like `managed_by_consul` (boolean) is better but a NULLable column looked better to add to existent (and large) tables.
=> Add source column to consul services and checks tables

crates/corrosion/src/command/consul/sync.rs
missed some cases in https://github.com/superfly/corrosion/pull/265
=> More conditions based on source column for consul sql updates

Cargo.lock, crates/corro-admin/src/lib.rs, crates/corro-agent/src/agent/handlers.rs, crates/corro-agent/src/agent/util.rs, crates/corro-agent/src/api/public/mod.rs, crates/corro-pg/Cargo.toml, crates/corro-pg/src/lib.rs, crates/corro-types/src/agent.rs, crates/corro-types/src/config.rs, crates/corrosion/src/main.rs
- Uses more threads
- Uses `spawn_blocking` instead of `block_in_place` in `corro-pg`
- Processes items faster and in smaller batches
=> Don't use `block_in_place` for long running blocking tasks

Cargo.lock, crates/corro-agent/src/agent/handlers.rs, crates/corro-agent/src/agent/tests.rs, crates/corro-agent/src/api/peer.rs, crates/corro-agent/src/api/public/mod.rs, crates/corro-agent/src/api/public/pubsub.rs, crates/corro-api-types/Cargo.toml, crates/corro-api-types/src/lib.rs, crates/corro-base-types/src/lib.rs, crates/corro-types/src/broadcast.rs, crates/corro-types/src/change.rs, crates/corro-types/src/pubsub.rs, crates/corro-types/src/updates.rs, crates/sqlite-pool/src/config.rs
This PR moves some code around to remove dependency on unstable Rust
toolchain in the corro-api-types crate.
The Step trait has been changed recently and it makes it impossible to
update Rust toolchain in corro-api-types/corro-client consumers without
first updating it in Corrosion to a compatible version.
=> corro-api-types: remove dependency on unstable Rust

crates/corro-agent/src/agent/handlers.rs, crates/corro-agent/src/api/public/mod.rs
This pull request updates some settings around wal checkpoint
qw set the busy timeout based on what the current size of the wal size, doubling the timeout with every extra gigabyte so we give any current readers not on the latest snapshot to complete so the wal_checkpoint can proceed.
@PeterCxy comment from a related PR:
busy_handler of checkpoints will wait until all readers are on the same latest snapshot, NOT when all readers complete. With huge subs we often have readers that take very long to complete, and in that case we might keep missing checkpoints until the WAL blows up in size, slowing down readers even further.
Because we don't actually need to wait for all readers to fully complete, and it doesn't block new readers (they'll be on the new snapshot), try increasing the timeout …
=> Update settings around wal checkpoint in sql

Cargo.lock, crates/corro-admin/Cargo.toml, crates/corro-admin/src/lib.rs, crates/corrosion/src/command/agent.rs, crates/corrosion/src/main.rs
This pull request adds two commands `corrosion log set <FILTER>` and `corrosion log reset` to dynamically set the log filtering when corrosion is running, which can be helpful during debugging
=> Add cli command to change log level

doc/crdts.md
Hey :wave: 
I found a subtle typo in `crdts.md` where a reference to the `site_id` was written as `side_id`.
=> [Docs] Fix typo in `crdts.md` where `site_id` is written as `side_id`

Cargo.lock, crates/corro-agent/src/agent/run_root.rs, crates/corro-agent/src/agent/util.rs, crates/corro-agent/src/api/public/mod.rs, crates/corro-client/Cargo.toml, crates/corro-client/src/lib.rs, crates/corro-tests/src/lib.rs
This pull request moves the code that applies the schema on startup. Sometimes we can fail to process requests and changes from other nodes because the schema isn't loaded yet.
=> Apply schema before starting http api handler

Cargo.lock, crates/corro-agent/Cargo.toml, crates/corro-agent/src/agent/run_root.rs, crates/corro-agent/src/agent/util.rs, crates/corro-client/Cargo.toml, crates/corro-client/src/lib.rs, crates/corro-utils/Cargo.toml, crates/corro-utils/src/lib.rs
This pulls way too much excessive stuff into the proxy and causes
it to fail automatic security audit.
Instead, move the utils that have to be shared between the agent and
the client into a separate small crate.
=> corro-client: don't depend on corro-agent

Cargo.lock, crates/corro-admin/Cargo.toml, crates/corro-admin/src/lib.rs, crates/corro-agent/src/agent/bi.rs, crates/corro-agent/src/agent/run_root.rs, crates/corro-agent/src/agent/setup.rs, crates/corro-agent/src/api/peer/follow.rs, crates/corro-agent/src/api/peer/mod.rs, crates/corro-tests/src/lib.rs, crates/corro-types/src/broadcast.rs, crates/corro-types/src/config.rs, crates/corrosion/src/command/agent.rs, crates/corrosion/src/main.rs
Allows a node to follow another, not necessarily in the same cluster.
=> Add `Follow` peer API

crates/corro-client/src/lib.rs, flake.nix
- flake.nix: use Rust toolchain specified in rust-toolchain.toml
- corro-client: add a function to create Corrosion client with user-provided pool
=> Allow to create CorrosionClient with user-provided SQLite pool

crates/corro-agent/src/agent/run_root.rs, crates/corro-pg/src/lib.rs, crates/corro-types/src/agent.rs, crates/corro-types/src/config.rs
As the title says, this PR makes it possible to spawn multiple PostgreSQL server endpoints, some of which may be readonly. Readonly mode is implemented by setting the readonly flag on the underlying SQLite connection, so that there's absolutely no possibility of accidentally running a write transaction using a readonly server.
=> Add support for multiple PostgreSQL endpoints and readonly mode

crates/corro-agent/src/agent/handlers.rs
The intent seems to be that latest changes are kept in `seen` when the cache is cleared with `IndexMap::split_off`, but `remove_entry` is the same thing as `swap_remove_entry` so it's possibly moving the latest seen change somewhere at the front of the map.
The removal will be slower (`O(n)` vs `O(1)`) but I assume that it does not grow too large as it seems to be trimmed every 10 ms to 2000 by default.
Alternatively, the entry could just not be removed at all to prevent both the move and move of the last element.
I've also replaced `split_off` with `drain` so that the map's allocation can be reused.
=> Optimize the seen cache in `handle_changes`

.antithesis/client/rust-load-generator/src/main.rs, Cargo.toml, crates/corro-agent/Cargo.toml, crates/corro-agent/src/agent/handlers.rs, crates/corro-agent/src/agent/setup.rs, crates/corro-agent/src/agent/tests.rs, crates/corro-agent/src/agent/util.rs, crates/corro-agent/src/api/peer/mod.rs, crates/corro-agent/src/api/public/mod.rs, crates/corro-agent/src/api/public/pubsub.rs, crates/corro-agent/src/broadcast/mod.rs, crates/corro-agent/src/lib.rs, crates/corro-api-types/src/lib.rs, crates/corro-base-types/src/lib.rs, crates/corro-client/Cargo.toml, crates/corro-client/src/lib.rs, crates/corro-devcluster/src/main.rs, crates/corro-pg/Cargo.toml, crates/corro-pg/src/lib.rs, crates/corro-types/Cargo.toml, crates/corro-types/src/agent.rs, crates/corro-types/src/broadcast.rs, crates/corro-types/src/change.rs, crates/corro-types/src/pubsub.rs, crates/corro-types/src/schema.rs, crates/corro-types/src/sqlite.rs, crates/corro-types/src/sync.rs, crates/corro-types/src/updates.rs, crates/sqlite-pool/src/lib.rs, rust-toolchain.toml
- **Remove need for iter::Step from CrsqlDbVersion**
- **Same for CrsqlSeq**
- **Remove no longer needed toolchain spec**
- **cargo fmt**
This PR removes the need for nightly by providing a simple implementation of a chunked iterator. I've implemented it on top of a simple `InclusiveRange` type that is convertible to and from `std::ops::RangeInclusive<u64>`. This could also be done via a regular function, since the use of the chunked iteration is only called in one location, let me know if you want me to change to that instead. The code was not formatted due to the reliance on the (almost year old) nightly version used, let me know if you want me to revert that commit to make the PR smaller.
=> Remove reliance on unstable traits

crates/corro-pg/src/lib.rs
Ideally we should have a wrapper that aborts these automatically on drop, but for now this should fix the bug at hand.
=> Abort PG TCP connection loops when message-handling exits

crates/corro-types/src/pubsub.rs
The `pack_column` function keeps all bytes for negative integers but truncates the zeros for positve integers. The [Bytes get_int](https://github.com/tokio-rs/bytes/pull/732) function previously used has been updated to do a sign extension for when the number of bits are less than 64, and this would cause some positive integers (with 1 as the msb) from the db to be changed to negative integers when unpacked. This pull request fixes it by doing a `uint` conversion which would add back the zeros.
=> Parse integers as uint first in `pack_columns` to prevent sign extension

crates/corro-agent/src/api/public/pubsub.rs
Fixes the bug where an failed resubscription attempt can cause the inability to subscribe to the given query in the future.
=> Clean up sub when broadcaster was not created

crates/corro-agent/src/api/public/mod.rs
The function is only called once, `Fn` places unnecessary restrictions since it means it can be called multiple times.
=> Use correct call type
