superfly/corrosion

- .buildkite/upload.sh
- README.md
> Remove a few "corrosion2" mentions, tweak readme

- crates/corro-agent/src/agent.rs
- crates/corro-agent/src/api/peer.rs
- crates/corro-agent/src/api/public/mod.rs
- crates/corro-api-types/src/lib.rs
This has several advantages such as higher throughput for many small changes.
> Chunk changes by byte size instead of number of changes

- crates/corro-agent/src/agent.rs
- crates/corro-agent/src/api/peer.rs
- crates/corro-agent/src/api/public/mod.rs
- crates/corro-agent/src/transport.rs
- crates/corro-types/src/agent.rs
- crates/corro-types/src/broadcast.rs
Adapts the buffer size for changes based on how fast the other sync end is responding.
Processes synchronization and broadcasts more efficiently.
> Adaptive chunking

- README.md
- doc/crdts.md
- Explain how conflict resolution happen
- Small README changes
> Small doc tweaks

- Cargo.lock
- Cargo.toml
- crates/corro-agent/src/api/public/mod.rs
- crates/corro-pg/Cargo.toml
- crates/corro-pg/src/lib.rs
- crates/corro-pg/src/vtab/mod.rs
- crates/corro-pg/src/vtab/pg_class.rs
- crates/corro-pg/src/vtab/pg_database.rs
- crates/corro-pg/src/vtab/pg_namespace.rs
- crates/corro-pg/src/vtab/pg_range.rs
- crates/corro-pg/src/vtab/pg_type.rs
- crates/corro-types/src/schema.rs
Supports more types, responds with the format requested. This fixes many issues w/ the golang lib/pq driver.
> PostgreSQL wire protocol API fixes and tweaks

- Cargo.lock
- crates/corro-agent/src/agent.rs
- crates/corro-agent/src/api/peer.rs
- crates/corro-agent/src/api/public/mod.rs
- crates/corro-agent/src/api/public/pubsub.rs
- crates/corro-pg/Cargo.toml
- crates/corro-pg/src/lib.rs
- crates/corro-types/src/agent.rs
- crates/corro-types/src/change.rs
- crates/corro-types/src/pubsub.rs
- crates/corro-types/src/sqlite.rs
- crates/corrosion/src/command/consul/sync.rs
- crates/corrosion/src/main.rs
Many improvements to make subscriptions more reliable and less lock-heavy.
> Subscriptions improvements

- crates/corro-agent/src/agent.rs
- crates/corro-agent/src/broadcast/mod.rs
- crates/corro-api-types/src/lib.rs
- crates/corrosion/src/main.rs
Sending a BLOB would send invalid data.
> Fix corrupt changeset

- crates/corro-agent/src/agent.rs
- crates/corro-agent/src/api/public/mod.rs
- crates/corro-agent/src/api/public/pubsub.rs
- crates/corro-agent/src/broadcast/mod.rs
- crates/corro-types/src/pubsub.rs
- crates/corro-types/src/sqlite.rs
Creates the proper indexes, uses non-immediate transactions to run the initial query.
> More subs tweaks

- crates/corro-api-types/src/sqlite.rs
- crates/corro-types/src/pubsub.rs
- crates/corrosion/src/command/consul/sync.rs
There was an issue where it only showed a delete for the first delete row.
> Make sure delete changes are deletes for every deleted row

- crates/sqlite3-restore/src/lib.rs
There are no headers to look at on the destination file if it was empty to begin with.
> Skip everything when storing to an inexistent DB

- crates/sqlite-pool/src/lib.rs
Let's see if this has any effect.
> Don't query SQLite in pool's recycle

- crates/corrosion/src/main.rs
A few improvements to the restore process
> Restore replace ordinal 0

- crates/corro-client/src/lib.rs
- crates/corro-client/src/sub.rs
- crates/corrosion/src/main.rs
This is useful for public DNS to fallback to HTTP queries until the
state is fully loaded via subscription.
> corro-client: support typed query results

- crates/corro-types/src/schema.rs
If you're adding "virtual" columns, there's no need to use crsql's migration mechanism since those columns are not stored in clock tables.
> Faster schema changes when adding only generated columns

- crates/corro-agent/src/api/public/pubsub.rs
This reverts commit dfd9e8958706532c915fc158227158229d814218.
> Revert "Simplify subscription creation to remove a write lock"

- Cargo.lock
- Cargo.toml
- crates/corro-agent/src/agent/metrics.rs
- crates/corrosion/src/command/agent.rs
- Adds git info to build info metrics
- Adds db and WAL size metrics
> More metrics (build info, db size)

- crates/corro-types/src/pubsub.rs
We already do this during insert, do it also doing delete. Otherwise,
a subscription with a join where we can have NULL primary keys in a
joined table skips delete as "DELETE WHERE pk IN (pks)" doesn't match
NULL primary keys.
> subs: coalesce NULL primary keys to "" during delete

- crates/corro-types/src/config.rs
- crates/corro-types/src/pubsub.rs
- subs: put subscription's where clause into parens in modified query
- subs: clear INDEXED BY in sub queries
> Subscription optimizations

- crates/corro-types/src/pubsub.rs
So we don't have to run them manually each time we need to verify the
subscription is efficient.
> Dump query plan for each subscription into logs

- crates/corro-agent/src/agent/run_root.rs
- crates/corro-agent/src/agent/setup.rs
- crates/corro-agent/src/api/public/pubsub.rs
- crates/corro-types/src/agent.rs
This PR aims at reducing the requirements for starting the API and restoring subscriptions by lazily loading the current node's versions.
> Lazy loading current actor's `BookedVersions`

- crates/corro-agent/src/agent/run_root.rs
- crates/corro-agent/src/agent/setup.rs
- crates/corro-agent/src/agent/util.rs
- crates/corrosion/src/command/agent.rs
- crates/corrosion/src/main.rs
Misread the source on TcpListener, need to bind different listeners.
> Actually bind to more than 1 ip

- Cargo.lock
- Cargo.toml
- crates/corro-admin/Cargo.toml
- crates/corro-admin/src/lib.rs
- crates/corro-agent/src/agent/bi.rs
- crates/corro-agent/src/agent/handlers.rs
- crates/corro-agent/src/agent/metrics.rs
- crates/corro-agent/src/agent/run_root.rs
- crates/corro-agent/src/agent/setup.rs
- crates/corro-agent/src/agent/tests.rs
- crates/corro-agent/src/agent/uni.rs
- crates/corro-agent/src/agent/util.rs
- crates/corro-agent/src/api/peer.rs
- crates/corro-agent/src/api/public/mod.rs
- crates/corro-api-types/src/lib.rs
- crates/corro-pg/src/lib.rs
- crates/corro-tests/src/lib.rs
- crates/corro-types/src/agent.rs
- crates/corro-types/src/pubsub.rs
- crates/corro-types/src/sqlite.rs
- crates/corrosion/Cargo.toml
- crates/corrosion/src/command/agent.rs
- crates/corrosion/src/main.rs
This PR:
- Much more efficiently fetches versions to send to other nodes when requested via sync
- Batches emptied versions together
> Sync improvements

- crates/corro-admin/src/lib.rs
- crates/corro-agent/src/agent/bi.rs
- crates/corro-agent/src/agent/uni.rs
- crates/corro-agent/src/api/peer.rs
- crates/corro-agent/src/broadcast/mod.rs
- crates/corrosion/src/admin.rs
> Use big length delimited codec frame sizes

- crates/corro-admin/src/lib.rs
- crates/corro-agent/src/agent/handlers.rs
- crates/corro-agent/src/agent/run_root.rs
- crates/corro-agent/src/agent/setup.rs
- crates/corro-agent/src/agent/tests.rs
- crates/corro-agent/src/agent/util.rs
- crates/corro-agent/src/api/peer.rs
- crates/corro-agent/src/api/public/mod.rs
- crates/corro-pg/src/lib.rs
- crates/corro-types/src/agent.rs
- crates/corro-types/src/sync.rs
This will warn if there are any locks held for a long time, every minute.
> Monitor lock registry for longly held locks

- Cargo.lock
- Cargo.toml
- crates/corro-agent/Cargo.toml
- crates/corro-agent/src/agent/bootstrap.rs
- crates/corro-client/Cargo.toml
- crates/corro-client/src/lib.rs
trust-dns-resolver is renamed and no longer maintained.
> Switch trust-dns-resolver to hickory-resolver

- crates/backoff/src/lib.rs
Fix problems mentioned in #310 .
> Fix inconsistent comment in backoff crate

- Cargo.lock
- Cargo.toml
- crates/corro-api-types/Cargo.toml
- crates/corro-api-types/src/lib.rs
- crates/corro-types/src/broadcast.rs
- crates/corro-types/src/change.rs
- crates/corro-types/src/pubsub.rs
- crates/corro-types/src/updates.rs
There is a newer version, but it has some incompatible API changes
so for now I'm bumping rusqlite to this version to unblock the proxy.
> Bump rusqlite to 0.33.0

- crates/corro-agent/src/api/public/pubsub.rs
- crates/corro-api-types/src/lib.rs
- crates/corro-types/src/pubsub.rs
> Revert subs changes

- crates/corro-types/src/pubsub.rs
PR #339  introduced a [change](https://github.com/superfly/corrosion/pull/339/files#diff-62ecb7c9894781392f1558f9a7345acca01335ed0078cc7a75366a9f03143797R1211) that prevented the subscription loop from calling the cleanup function when cancelled. This pull request fixes that.
> Run cleanup when subs gets cancelled

- crates/corro-agent/src/api/public/pubsub.rs
- crates/corro-api-types/src/lib.rs
- crates/corro-types/src/pubsub.rs
This pull request reapplies commits that were wrongly reverted in #356
> Return error if client tries to restart sub from a change id… 
